//lista de ejemplo para dar forma a las tarjetas. reemplazar por datos de db

export const ListaProductos =  [
    { nombre: 'Flautas', precio: 50, descripcion: 'Deliciosas flautas rellenas de carne o pollo.' },
    { nombre: 'Minion', precio: 30, descripcion: 'Galleta con forma de Minion, ideal para niños.' },
    { nombre: 'Figasas', precio: 40, descripcion: 'Panecillos suaves y esponjosos con un toque dulce.' },
    { nombre: 'Pizza muzza', precio: 120, descripcion: 'Pizza clásica con mozzarella derretida.' },
    { nombre: 'Palmeritas', precio: 45, descripcion: 'Hojaldre en forma de palmera, crujiente y dulce.' },
    { nombre: 'Medialunas manteca', precio: 35, descripcion: 'Medialunas suaves con un toque de manteca.' },
    { nombre: 'Pan negro', precio: 60, descripcion: 'Pan integral oscuro y denso, perfecto para sandwiches.' },
    { nombre: 'Scon naranja', precio: 55, descripcion: 'Scones aromatizados con naranja, ideales para el desayuno.' },
    { nombre: 'Empanadas capresse', precio: 80, descripcion: 'Empanadas rellenas con tomate, mozzarella y albahaca.' },
    { nombre: 'Empanadas arabes', precio: 85, descripcion: 'Empanadas rellenas con carne especiada al estilo árabe.' },
    { nombre: 'Medialunas jamon y queso', precio: 50, descripcion: 'Medialunas saladas rellenas de jamón y queso.' },
    { nombre: 'Chipacitos', precio: 60, descripcion: 'Pequeños panes de queso con un sabor único.' },
    { nombre: 'Pastra frola', precio: 70, descripcion: 'Tarta de membrillo con masa suave y dulce.' },
    { nombre: 'Ricota chica', precio: 55, descripcion: 'Ricota fresca y suave, ideal para postres o tartas.' },
    { nombre: 'Canoncitos', precio: 45, descripcion: 'Deliciosos canutillos rellenos de crema pastelera.' },
    { nombre: 'Criollos', precio: 50, descripcion: 'Panecillos suaves y ligeramente salados.' },
    { nombre: 'Scones jamon y queso', precio: 65, descripcion: 'Scones salados con jamón y queso.' },
    { nombre: 'Ricota chica ddl', precio: 60, descripcion: 'Ricota con dulce de leche, una combinación dulce y cremosa.' },
    { nombre: 'Culitos', precio: 40, descripcion: 'Pequeños panecillos dulces con azúcar glas.' },
    { nombre: 'Sacramentos', precio: 75, descripcion: 'Tartas saladas con un toque de queso y verduras.' },
    { nombre: 'Negritas', precio: 30, descripcion: 'Galletas de chocolate crujientes por fuera y suaves por dentro.' },
    { nombre: 'Scones pasas uva', precio: 65, descripcion: 'Scones con pasas de uva, perfectos para acompañar el té.' },
    { nombre: 'Budines chips', precio: 90, descripcion: 'Budín de chocolate con chips de chocolate.' },
    { nombre: 'Budin naranja', precio: 80, descripcion: 'Budín aromatizado con jugo de naranja, suave y esponjoso.' },
    { nombre: 'Budin marmolado', precio: 85, descripcion: 'Budín con mezcla de chocolate y vainilla, ideal para cualquier ocasión.' },
    { nombre: 'Budin amapola', precio: 80, descripcion: 'Budín con semillas de amapola, delicado y sabroso.' },
    { nombre: 'Rocetas', precio: 50, descripcion: 'Dulces crujientes con una capa de azúcar.' },
    { nombre: 'Prepizza tomate (x2)', precio: 100, descripcion: 'Base de pizza con salsa de tomate, lista para agregar tus ingredientes favoritos.' },
    { nombre: 'Bizcochos', precio: 40, descripcion: 'Bizcochos suaves y esponjosos, perfectos para el desayuno.' },
    { nombre: 'Pan mode blanco', precio: 70, descripcion: 'Pan blanco de miga suave, ideal para sandwiches.' },
    { nombre: 'Figasas chicas', precio: 35, descripcion: 'Panecillos pequeños y esponjosos, ideales para acompañar cualquier comida.' },
    { nombre: 'Ricota grande', precio: 90, descripcion: 'Ricota fresca en tamaño grande, perfecta para recetas o postres.' },
    { nombre: 'Ricota grande ddl', precio: 95, descripcion: 'Ricota con dulce de leche, ideal para postres.' },
    { nombre: 'Pan molde blanco', precio: 80, descripcion: 'Pan molde blanco, suave y esponjoso.' },
    { nombre: 'Facturas', precio: 60, descripcion: 'Variedad de facturas dulces, perfectas para el té.' },
    { nombre: 'Fautas', precio: 50, descripcion: 'Panecillos crujientes y ligeramente dulces.' },
    { nombre: 'Scon chips choco', precio: 75, descripcion: 'Scones con chips de chocolate.' },
    { nombre: 'Pan arabe blanco', precio: 85, descripcion: 'Pan árabe suave y esponjoso, ideal para envolver tus alimentos.' },
    { nombre: 'Budin limon', precio: 75, descripcion: 'Budín con un toque de limón, fresco y sabroso.' },
    { nombre: 'Relleno carne y pollo', precio: 120, descripcion: 'Relleno de carne y pollo, ideal para empanadas o tartas.' },
    { nombre: 'Empanadas jamon y queso', precio: 90, descripcion: 'Empanadas con relleno de jamón y queso.' },
    { nombre: 'Pepas', precio: 45, descripcion: 'Galletas con mermelada en el centro.' },
    { nombre: 'Tarta de manzana chica', precio: 110, descripcion: 'Tarta de manzana pequeña, ideal para postres personales.' },
    { nombre: 'Tarta de manzana grande', precio: 140, descripcion: 'Tarta de manzana grande, perfecta para compartir.' },
    { nombre: 'Merengue', precio: 50, descripcion: 'Merengue dulce y crujiente.' },
    { nombre: 'Rosetas', precio: 60, descripcion: 'Deliciosas rosetas de pan con azúcar.' },
    { nombre: 'Scon pasas de uva', precio: 65, descripcion: 'Scones con pasas de uva.' },
    { nombre: 'Empanadas pollo', precio: 80, descripcion: 'Empanadas rellenas con pollo sazonado.' },
    { nombre: 'Figuras', precio: 35, descripcion: 'Galletas de diferentes figuras, perfectas para niños.' },
    { nombre: 'Pizza muzarella', precio: 120, descripcion: 'Pizza con mozzarella derretida y una base crujiente.' },
    { nombre: 'Empanadas carne', precio: 100, descripcion: 'Empanadas rellenas con carne y especias.' },
    { nombre: 'Avena limon', precio: 45, descripcion: 'Avena con sabor a limón, ideal para un desayuno saludable.' },
    { nombre: 'Blister oreo', precio: 35, descripcion: 'Paquete de galletas Oreo, ideales para un snack.' },
    { nombre: 'Scones frutos secos', precio: 85, descripcion: 'Scones con una mezcla de frutos secos.' },
    { nombre: 'Pan molde salvado con almendra', precio: 90, descripcion: 'Pan integral con salvado y almendras.' },
    { nombre: 'Cuernitos', precio: 50, descripcion: 'Panecillos dulces con forma de cuerno.' },
    { nombre: 'Pizzetas tomate (x12)', precio: 130, descripcion: 'Pequeñas pizzetas con salsa de tomate, ideales para picoteo.' },
    { nombre: 'Pebetes', precio: 40, descripcion: 'Panecillos pequeños, perfectos para hacer mini sandwiches.' },
    { nombre: 'Scons chips chocolate', precio: 75, descripcion: 'Scones con chips de chocolate.' },
    { nombre: 'Bizcochos jamon y queso', precio: 70, descripcion: 'Bizcochos salados rellenos con jamón y queso.' },
    { nombre: 'Empanadas cebolla', precio: 85, descripcion: 'Empanadas rellenas de cebolla y queso.' },
    { nombre: 'Coquitos', precio: 60, descripcion: 'Galletas de coco con un toque dulce.' },
    { nombre: 'Avena naranja', precio: 45, descripcion: 'Avena con sabor a naranja.' },
    { nombre: 'Budin ingles', precio: 95, descripcion: 'Budín tradicional inglés con frutas secas.' },
    { nombre: 'Pan arabe negro', precio: 90, descripcion: 'Pan árabe oscuro y denso.' },
    { nombre: 'Empanadas arabe', precio: 90, descripcion: 'Empanadas con relleno árabe de carne.' },
    { nombre: 'Bizcochitos jamon y queso', precio: 75, descripcion: 'Bizcochitos salados rellenos de jamón y queso.' },
    { nombre: 'Pan molde salvado', precio: 80, descripcion: 'Pan molde integral con salvado.' },
    { nombre: 'Tarta manzana chica', precio: 110, descripcion: 'Tarta de manzana pequeña para porciones individuales.' },
    { nombre: 'Tarta manzana grande', precio: 140, descripcion: 'Tarta de manzana grande, ideal para compartir.' },
    { nombre: 'Anillos maicena chocolate blister', precio: 55, descripcion: 'Galletas de maicena con chocolate.' },
    { nombre: 'Alf. maicna blister', precio: 50, descripcion: 'Alfajores de maicena con dulce de leche.' },
    { nombre: 'Morron conserva', precio: 40, descripcion: 'Morrones en conserva, perfectos para agregar a ensaladas.' },
    { nombre: 'Morron p/ freezar', precio: 45, descripcion: 'Morrones listos para congelar y usar cuando lo necesites.' }
  ];
  
  